// The Decor Store's priced item list — one entry per `SCENE_SPRITES` key
// (`@/shared/aquarium`'s re-export of `scene/sprites/sprite-manifest.ts`).
// Imports only types + that plain-data manifest — never `SPRITE_SOURCES`
// (which carries RN `require()` calls) — so this stays runnable under plain
// Node for `scripts/verify-economy.ts`.
//
// Prices are anchored against a typical sale (~25-75 coins for a completed
// session at the default 25m duration — see `shared/economy/pricing.ts`'s
// worked examples): a 40-coin tuft is one short session, a 500-coin log is a
// weekend of focus or one long, rare sale.

import type { DecorItemDef } from "./types";

export const DECOR_CATALOG: readonly DecorItemDef[] = [
  {
    id: "grassTuft",
    name: "Grass Tuft",
    description: "A small clump of grass for the foreground.",
    rarity: { tier: "common" },
    price: 40,
    layers: ["mid", "frontMid", "front", "frontMost"],
    minScale: 0.6,
    defaultScale: 1,
    maxScale: 1.3,
    category: "plant",
  },
  {
    id: "mossBall",
    name: "Moss Ball",
    description: "A round marimo moss ball.",
    rarity: { tier: "common" },
    price: 60,
    layers: ["back", "backMid", "mid", "frontMid", "front", "frontMost"],
    minScale: 0.6,
    defaultScale: 1,
    maxScale: 1.3,
    category: "accent",
  },
  {
    id: "rockSmall",
    name: "Small Rock",
    description: "A modest stone for filling gaps.",
    rarity: { tier: "common" },
    price: 80,
    layers: ["back", "backMid", "mid", "frontMid", "front", "frontMost"],
    minScale: 0.6,
    defaultScale: 1,
    maxScale: 1.4,
    category: "hardscape",
  },
  {
    id: "leafyClump",
    name: "Leafy Clump",
    description: "A low, bushy clump of leaves.",
    rarity: { tier: "common" },
    price: 90,
    layers: ["back", "backMid", "mid", "frontMid", "front", "frontMost"],
    minScale: 0.6,
    defaultScale: 1,
    maxScale: 1.3,
    category: "plant",
  },
  {
    id: "fern",
    name: "Fern",
    description: "A feathery fern that sways in the current.",
    rarity: { tier: "uncommon" },
    price: 120,
    layers: ["mid", "frontMid", "front", "frontMost"],
    minScale: 0.6,
    defaultScale: 1,
    maxScale: 1.3,
    category: "plant",
  },
  {
    id: "anubiasA",
    name: "Anubias",
    description: "Broad, hardy leaves on a short stem.",
    rarity: { tier: "uncommon" },
    price: 140,
    layers: ["mid", "frontMid", "front", "frontMost"],
    minScale: 0.6,
    defaultScale: 1,
    maxScale: 1.3,
    category: "plant",
  },
  {
    id: "anubiasB",
    name: "Anubias Bunch",
    description: "A fuller cluster of anubias leaves.",
    rarity: { tier: "uncommon" },
    price: 150,
    layers: ["mid", "frontMid", "front", "frontMost"],
    minScale: 0.6,
    defaultScale: 1,
    maxScale: 1.2,
    category: "plant",
  },
  {
    id: "cabomba",
    name: "Cabomba",
    description: "Delicate, feathery underwater foliage.",
    rarity: { tier: "uncommon" },
    price: 160,
    layers: ["back", "backMid", "mid"],
    minScale: 0.6,
    defaultScale: 1,
    maxScale: 1.2,
    category: "plant",
  },
  {
    id: "grassSpiky",
    name: "Spiky Grass",
    description: "Tall, narrow blades that catch the light.",
    rarity: { tier: "uncommon" },
    price: 180,
    layers: ["mid", "frontMid", "front", "frontMost"],
    minScale: 0.6,
    defaultScale: 1,
    maxScale: 1.2,
    category: "plant",
  },
  {
    id: "rockA",
    name: "Rock",
    description: "A weathered aquarium stone.",
    rarity: { tier: "rare" },
    price: 200,
    layers: ["back", "backMid", "mid", "frontMid", "front", "frontMost"],
    minScale: 0.6,
    defaultScale: 1,
    maxScale: 1.3,
    category: "hardscape",
  },
  {
    id: "rockB",
    name: "Flat Rock",
    description: "A broad, flat-topped stone.",
    rarity: { tier: "rare" },
    price: 200,
    layers: ["back", "backMid", "mid", "frontMid", "front", "frontMost"],
    minScale: 0.6,
    defaultScale: 1,
    maxScale: 1.3,
    category: "hardscape",
  },
  {
    id: "leafyBush",
    name: "Leafy Bush",
    description: "A dense, rounded bush of leaves.",
    rarity: { tier: "rare" },
    price: 200,
    layers: ["mid", "frontMid", "front", "frontMost"],
    minScale: 0.6,
    defaultScale: 1,
    maxScale: 1.2,
    category: "plant",
  },
  {
    id: "driftwoodBranch2",
    name: "Driftwood Twig",
    description: "A slender, forked piece of driftwood.",
    rarity: { tier: "rare" },
    price: 240,
    layers: ["mid", "frontMid", "front", "frontMost"],
    minScale: 0.6,
    defaultScale: 1,
    maxScale: 1.2,
    category: "hardscape",
  },
  {
    id: "tallGrass",
    name: "Tall Grass",
    description: "A tall stand of swaying grass.",
    rarity: { tier: "rare" },
    price: 260,
    layers: ["mid", "frontMid", "front", "frontMost"],
    minScale: 0.5,
    defaultScale: 0.9,
    maxScale: 1.1,
    // Tall in a short landscape canvas without this — see `SpritePlacement.maxHeightFraction`.
    maxHeightFraction: 0.7,
    category: "plant",
  },
  {
    id: "kelp",
    name: "Kelp",
    description: "A tall stalk of swaying kelp — tall enough for a snail to climb.",
    rarity: { tier: "epic" },
    price: 300,
    layers: ["back", "backMid", "mid"],
    minScale: 0.5,
    defaultScale: 0.9,
    maxScale: 1.1,
    maxHeightFraction: 0.75,
    category: "plant",
  },
  {
    id: "rotalaTall",
    name: "Tall Rotala",
    description: "A tall stem plant with fine, feathery leaves.",
    rarity: { tier: "epic" },
    price: 320,
    layers: ["back", "backMid", "mid"],
    minScale: 0.5,
    defaultScale: 0.9,
    maxScale: 1.1,
    maxHeightFraction: 0.7,
    category: "plant",
  },
  {
    id: "driftwoodBranch",
    name: "Driftwood Branch",
    description: "A tall, gnarled branch of driftwood.",
    rarity: { tier: "epic" },
    price: 360,
    layers: ["mid", "frontMid", "front", "frontMost"],
    minScale: 0.5,
    defaultScale: 0.9,
    maxScale: 1.1,
    maxHeightFraction: 0.7,
    category: "hardscape",
  },
  {
    id: "rockHuge",
    name: "Boulder",
    description: "A commanding centerpiece boulder.",
    rarity: { tier: "legendary" },
    price: 420,
    layers: ["mid", "frontMid", "front", "frontMost"],
    minScale: 0.6,
    defaultScale: 1,
    maxScale: 1.2,
    category: "hardscape",
  },
  {
    id: "driftwoodLog",
    name: "Driftwood Log",
    description: "A massive, sculptural log — the tank's centerpiece.",
    rarity: { tier: "legendary" },
    price: 500,
    layers: ["mid", "frontMid", "front", "frontMost"],
    minScale: 0.5,
    defaultScale: 0.85,
    maxScale: 1,
    maxHeightFraction: 0.6,
    category: "hardscape",
  },
  {
    id: "sandPatch",
    name: "Sand Patch",
    description: "A lighter patch of substrate.",
    rarity: { tier: "common" },
    price: 30,
    layers: ["back", "backMid", "mid"],
    minScale: 0.3,
    defaultScale: 0.5,
    // Small on purpose — this asset is a thin oval that stretches badly at
    // large sizes (see `sprite-layers.tsx`'s dedicated sand-patch note).
    maxScale: 0.6,
    category: "accent",
  },
];

const CATALOG_BY_ID = new Map(DECOR_CATALOG.map((def) => [def.id as string, def]));

export function getDecorDef(id: string): DecorItemDef | undefined {
  return CATALOG_BY_ID.get(id);
}
