// Generates src/docs/fish-preview.html — a static SVG gallery of every fish
// color × life stage (+ dead + locked silhouette) plus rolled-trait showcases,
// rendered from the SAME render-spec the app uses. Run: yarn fish:preview

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import {
  BODY_DEFS,
  COLOR_DEFS,
  DORSAL_DEFS,
  standardTraits,
  TAIL_DEFS,
} from "../src/shared/fish/catalog";
import { RARITY_COLORS, formatRarity } from "../src/shared/fish/rarity";
import type { FishTraits, UnlockRule } from "../src/shared/fish/types";
import { fishSvg } from "./lib/fish-svg";

function unlockHintText(rule: UnlockRule): string {
  switch (rule.type) {
    case "default":
      return "Starter";
    case "sessionMinutes":
      return `Single ${rule.minutes}m session`;
    case "totalHours":
      return `${rule.hours}h total focus`;
    case "streakDays":
      return `${rule.days}-day streak`;
    case "streakOrGrant":
      return `${rule.days}-day streak / event`;
  }
}

function badge(text: string, color: string): string {
  return `<span class="badge" style="background:${color}22;color:${color};border-color:${color}55">${text}</span>`;
}

const colorRows = COLOR_DEFS.map((def) => {
  const traits = standardTraits(def.id);
  const cells = [
    fishSvg(traits, def, { stage: "adult" }),
    fishSvg(traits, def, { stage: "juvenile" }),
    fishSvg(traits, def, { stage: "fry" }),
    fishSvg(traits, def, { stage: "egg" }),
    fishSvg(traits, def, { stage: "adult", dead: true }),
    fishSvg(traits, def, { stage: "adult", silhouette: true }),
  ]
    .map((svg) => `<td>${svg}</td>`)
    .join("");
  const rarityColor = RARITY_COLORS[def.rarity.tier];
  return `<tr>
    <td class="meta">
      <div class="order">#${def.order}</div>
      <div class="name">${def.name}</div>
      ${badge(formatRarity(def.rarity), rarityColor)}
      <div class="hint">${unlockHintText(def.unlock)}</div>
      <div class="desc">${def.description}</div>
    </td>${cells}</tr>`;
}).join("\n");

const showcases: { label: string; traits: FishTraits }[] = [
  { label: "Balloon body (Gold Dust)", traits: { ...standardTraits("goldDust"), body: "balloon" } },
  { label: "Lyretail (Platinum)", traits: { ...standardTraits("platinum"), tail: "lyretail" } },
  { label: "Sailfin (Black)", traits: { ...standardTraits("black"), dorsal: "sailfin" } },
  {
    label: "All rare rolls (Sanke)",
    traits: { color: "sanke", body: "balloon", tail: "lyretail", dorsal: "sailfin" },
  },
  {
    label: "Shadow Veil, lyretail + sailfin",
    traits: { ...standardTraits("shadowVeil"), tail: "lyretail", dorsal: "sailfin" },
  },
];

const showcaseCells = showcases
  .map(({ label, traits }) => {
    const def = COLOR_DEFS.find((d) => d.id === traits.color)!;
    return `<div class="show"><div>${fishSvg(traits, def)}</div><div class="hint">${label}</div></div>`;
  })
  .join("");

const oddsRows = [
  ...BODY_DEFS.map((d) => ({ axis: "Body", ...d })),
  ...TAIL_DEFS.map((d) => ({ axis: "Tail", ...d })),
  ...DORSAL_DEFS.map((d) => ({ axis: "Dorsal", ...d })),
]
  .map(
    (d) =>
      `<tr><td>${d.axis}</td><td>${d.name}</td><td>${badge(formatRarity(d.rarity), RARITY_COLORS[d.rarity.tier])}</td><td>${d.weight}%</td></tr>`,
  )
  .join("");

const html = `<!doctype html>
<html><head><meta charset="utf-8"><title>Molly fish preview</title>
<style>
  body { margin:0; padding:24px; font-family: -apple-system, "Segoe UI", sans-serif;
         background: linear-gradient(180deg, #0b3a5c 0%, #063049 45%, #02131f 100%);
         color:#eaf6ff; min-height:100vh; }
  h1 { font-size:22px; } h2 { font-size:16px; margin-top:32px; color:#8fb3cc; }
  table { border-collapse: collapse; }
  td { padding:6px 10px; vertical-align: middle; }
  thead td { color:#8fb3cc; font-size:12px; }
  tbody tr { border-top: 1px solid rgba(255,255,255,0.08); }
  .meta { min-width: 180px; }
  .order { color:#54788f; font-size:11px; }
  .name { font-weight:700; font-size:15px; }
  .hint { color:#8fb3cc; font-size:11px; margin-top:2px; }
  .desc { color:#54788f; font-size:11px; margin-top:2px; max-width:190px; }
  .badge { display:inline-block; font-size:10px; font-weight:700; padding:1px 8px;
           border-radius:99px; border:1px solid; margin-top:3px; }
  .shows { display:flex; gap:16px; flex-wrap:wrap; }
  .show { text-align:center; }
  .odds td { font-size:12px; }
</style></head><body>
<h1>🐟 Molly fish preview — ${COLOR_DEFS.length} colors</h1>
<p class="hint">Generated by scripts/fish-preview.ts from src/shared/fish/render-spec.ts — the exact drawing code the app uses. Regenerate with <code>yarn fish:preview</code>.</p>
<table>
<thead><tr><td>Variety</td><td>Adult</td><td>Juvenile</td><td>Fry</td><td>Egg</td><td>Dead</td><td>Locked</td></tr></thead>
<tbody>
${colorRows}
</tbody></table>
<h2 id="showcases">Rolled-trait showcases</h2>
<div class="shows">${showcaseCells}</div>
<h2 id="odds">Roll odds</h2>
<table class="odds"><thead><tr><td>Axis</td><td>Trait</td><td>Rarity</td><td>Weight</td></tr></thead>
<tbody>${oddsRows}</tbody></table>
</body></html>`;

const outPath = join(dirname(fileURLToPath(import.meta.url)), "../src/docs/fish-preview.html");
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, html);
console.log(`Wrote ${outPath}`);
