// Generates src/docs/fish-3d-demo.html — a browser preview of the app's 3D
// fish, no dev server or device needed. Run: yarn fish:3d-demo
//
// Genuinely shares code with the shipping app now, not a disconnected spike:
// the mesh (src/shared/components/tank/fish-mesh-3d.ts) and swim physics
// (swim-model.ts) are the exact same modules the real 2D/3D toggle in the
// app uses (see src/shared/components/tank/fish-3d.tsx and
// tank-canvas-3d.tsx) — only the R3F/expo-gl rendering plumbing differs from
// the in-app version, since this runs in a plain browser via raw three.js.
// render-spec.ts stays the 2D source of truth for the fixed-shape trait
// system (body/tail/dorsal variants, procedural patterns) — the 3D mesh
// doesn't attempt that parity, see fish-mesh-3d.ts's header for why.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import * as esbuild from "esbuild";

import { COLOR_DEFS } from "../src/shared/fish/catalog";
import type { DorsalId, TailId } from "../src/shared/fish/types";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");

// One of every variety, so the preview shows the full colour range rather
// than a random handful. Every third fish gets the lyretail tail and every
// fourth the sailfin dorsal (overlapping on some), so the roster actually
// shows off both 3D trait shapes rather than only ever rendering the plain
// round/standard pair.
const FISH_COUNT = COLOR_DEFS.length;
const specs = COLOR_DEFS.map((def, i) => {
  const tail: TailId = i % 3 === 0 ? "lyretail" : "round";
  const dorsal: DorsalId = i % 4 === 0 ? "sailfin" : "standard";
  return {
    id: `demo3d-${i}-${def.id}`,
    palette: def.palette,
    traits: { color: def.id, body: "standard" as const, tail, dorsal, patternSeed: 0 },
  };
});

// The model is embedded as base64 rather than fetched — this page is meant to
// be a single self-contained file with no server, and it's only 43KB.
const glbBase64 = readFileSync(join(root, "assets/models/short_molly.glb")).toString("base64");

// ---------------------------------------------------------------------------
// Bundle the driver (three.js + OrbitControls + the real swim-model.ts +
// fish-3d.ts) plus a tiny virtual entry that mounts it against the page's
// canvas once the DOM is ready.
// ---------------------------------------------------------------------------

const bundle = esbuild.buildSync({
  stdin: {
    contents: `
      import { mountTankDemo } from "./lib/fish-3d-driver";
      const specs = ${JSON.stringify(specs)};
      const glbBytes = Uint8Array.from(atob(${JSON.stringify(glbBase64)}), (c) => c.charCodeAt(0)).buffer;
      window.addEventListener("DOMContentLoaded", () => {
        const canvas = document.getElementById("scene");
        mountTankDemo(canvas, specs, undefined, glbBytes);
      });
    `,
    resolveDir: here,
    loader: "ts",
  },
  bundle: true,
  write: false,
  format: "iife",
  platform: "browser",
  target: "es2020",
  alias: {
    "@/shared/constants/tank": join(root, "src/shared/constants/tank.ts"),
  },
});
const driverJs = bundle.outputFiles[0].text;

const html = `<!doctype html>
<html><head><meta charset="utf-8"><title>Molly 3D fish demo</title>
<style>
  html, body { margin:0; height:100%; overflow:hidden; background:#04121d; font-family: -apple-system, "Segoe UI", sans-serif; color:#eaf6ff; }
  canvas { display:block; width:100%; height:100%; }
  #hud { position:fixed; top:0; left:0; right:0; padding:12px 20px; pointer-events:none; }
  #hud h1 { font-size:16px; margin:0 0 4px; }
  #hud p { font-size:12px; color:#8fb3cc; margin:0; max-width:640px; }
  #hud .hint { color:#54788f; margin-top:4px; }
</style></head><body>
<canvas id="scene"></canvas>
<div id="hud">
  <h1>🐟 Molly 3D fish demo — ${FISH_COUNT} fish, real geometry</h1>
  <p>Procedural 3D mesh (not the app's shipping art) driven by the real swim-model.ts physics —
  genuine per-vertex body undulation, true 3D turns, real camera depth. Generated by
  scripts/fish-3d-demo.ts. Regenerate with <code>yarn fish:3d-demo</code>.</p>
  <p class="hint">Drag to orbit, scroll to zoom.</p>
</div>
<script>${driverJs}</script>
</body></html>`;

const outPath = join(root, "src/docs/fish-3d-demo.html");
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, html);
console.log(`Wrote ${outPath}`);
